### PR TITLE
fix: fix age calculation using timezone

### LINKED ISSUE #1013: Error in age calculation
Hi Guys, The age calculation just uses the year. Unfortunately this make me a year older than I am until October.
Regards,
Tim

### PR DESCRIPTION
**Pull request by asbiin**
This fix #1013

You fool, don't forget these steps:

- [x] Unit tests
- [ ] Tests with Cypress
- [ ] Documentation
- [ ] Dummy data

### CODE REVIEW

File: tests/Unit/Helpers/BirthdayHelperTest.php [hunk 1]
```diff
@@ -53,4 +53,75 @@ public function it_indicates_if_a_birthday_occurs_in_a_range_of_dates(): void
         $this->assertTrue(BirthdayHelper::isBirthdayInRange($date, $min, $max));
         $this->assertFalse(BirthdayHelper::isBirthdayInRange($date, $min->addMonth(), $max->addMonth()));
     }
+
+    /** @test */
+    public function it_calculate_the_age_prior_to_the_birthday(): void
```
Comment (djaiss) [inline tests/Unit/Helpers/BirthdayHelperTest.php:58]:
```suggestion
    public function it_calculates_the_age_prior_to_the_birthday(): void
```

File: tests/Unit/Helpers/BirthdayHelperTest.php [hunk 2]
```diff
@@ -53,4 +53,75 @@ public function it_indicates_if_a_birthday_occurs_in_a_range_of_dates(): void
...
+        $date = Carbon::create(1990, 5, 1);
+
+        $this->assertEquals(29, BirthdayHelper::age($date));
+        $this->assertEquals(29, BirthdayHelper::age($date, 'UTC'));
+        $this->assertEquals(29, BirthdayHelper::age($date, 'Europe/Paris'));
+        $this->assertEquals(29, BirthdayHelper::age($date, 'America/Chicago'));
+    }
+
+    /** @test */
+    public function it_calculate_the_age_on_birthday_for_local_time(): void
```
Comment (djaiss) [inline tests/Unit/Helpers/BirthdayHelperTest.php:71]:
```suggestion
    public function it_calculates_the_age_on_birthday_for_local_time(): void
```

File: tests/Unit/Helpers/BirthdayHelperTest.php [hunk 3]
```diff
@@ -53,4 +53,75 @@ public function it_indicates_if_a_birthday_occurs_in_a_range_of_dates(): void
...
+
+        // It's already 2020-05-01 for Paris
+        $this->assertEquals(30, BirthdayHelper::age($date, 'Europe/Paris'));
+
+        // It's still 2020-04-30 for Chicago
+        $this->assertEquals(29, BirthdayHelper::age($date, 'America/Chicago'));
+    }
+
+    /** @test */
+    public function it_calculate_the_age_on_birthday(): void
```
Comment (djaiss) [inline tests/Unit/Helpers/BirthdayHelperTest.php:88]:
```suggestion
    public function it_calculates_the_age_on_birthday(): void
```

File: tests/Unit/Helpers/BirthdayHelperTest.php [hunk 4]
```diff
@@ -53,4 +53,75 @@ public function it_indicates_if_a_birthday_occurs_in_a_range_of_dates(): void
...
+        $this->assertEquals(30, BirthdayHelper::age($date));
+        $this->assertEquals(30, BirthdayHelper::age($date, 'UTC'));
+        $this->assertEquals(30, BirthdayHelper::age($date, 'Europe/Paris'));
+
+        // It's still 2020-04-30 for Chicago
+        $this->assertEquals(29, BirthdayHelper::age($date, 'America/Chicago'));
+    }
+
+    /** @test */
+    public function it_calculate_the_age_on_birthday_later(): void
```
Comment (djaiss) [inline tests/Unit/Helpers/BirthdayHelperTest.php:103]:
```suggestion
    public function it_calculates_the_age_on_birthday_later(): void
```

File: tests/Unit/Helpers/BirthdayHelperTest.php [hunk 5]
```diff
@@ -53,4 +53,75 @@ public function it_indicates_if_a_birthday_occurs_in_a_range_of_dates(): void
...
+        $date = Carbon::create(1990, 5, 1);
+
+        $this->assertEquals(30, BirthdayHelper::age($date));
+        $this->assertEquals(30, BirthdayHelper::age($date, 'UTC'));
+        $this->assertEquals(30, BirthdayHelper::age($date, 'Europe/Paris'));
+        $this->assertEquals(30, BirthdayHelper::age($date, 'America/Chicago'));
+    }
+
+    /** @test */
+    public function it_calculate_the_age_the_day_after(): void
```
Comment (djaiss) [inline tests/Unit/Helpers/BirthdayHelperTest.php:116]:
```suggestion
    public function it_calculates_the_age_the_day_after(): void
```

File: tests/Unit/ViewHelpers/Employee/EmployeeShowViewHelperTest.php [hunk 6]
```diff
@@ -84,6 +85,68 @@ public function it_gets_the_information_about_the_employee(): void
         $this->assertArrayHasKey('url', $array);
     }
 
+    /** @test */
+    public function it_calculate_the_age_of_the_employee(): void
```
Comment (djaiss) [inline tests/Unit/ViewHelpers/Employee/EmployeeShowViewHelperTest.php:89]:
```suggestion
    public function it_calculates_the_age_of_the_employee(): void
```

**Review by djaiss — COMMENTED** [review]
A few grammar mistakes, otherwise it's all good.
